feat: заменить иконку приложения, создать экран «Плейлист», список треков в плейлисте, Кнопка «Поделиться», редактирование плейлиста
mdorogov/PlaylistMaker pull request #22
Opened 2024-11-27 07:27 UTC by mdorogov

2024-11-27 08:38 UTC, DmitrijEgorow commented
- [ ] При открытии клавиатуры на экране поиска нижнее меню навигации должно скрываться за ней

https://github.com/user-attachments/assets/a8e4b0ce-7588-46df-8fb0-761f9eb31758

2024-11-27 08:38 UTC, DmitrijEgorow commented
- [ ] Не соответствует дизайну
![Screenshot_20241127_105857](https://github.com/user-attachments/assets/17158617-4cc1-4fb1-8b80-136209a2b952)

2024-11-27 08:39 UTC, DmitrijEgorow commented
- [ ] Плейлист не должен отбрасывать тень
![Screenshot_20241127_104156](https://github.com/user-attachments/assets/8afee12d-150a-4da3-a096-36dd554ade5c)

2024-11-27 08:40 UTC, DmitrijEgorow commented
- [ ] Кнопка сердечка не соответствует дизайну
![Screenshot_20241127_110235](https://github.com/user-attachments/assets/1d9e1dbd-7cc4-4de7-b48f-29cceb7a1170)

2024-11-27 08:42 UTC, DmitrijEgorow commented
- [ ] При удалении треков в одном плейлисте они удаляются во всех, приходим к неконсистентному состоянию
- [ ] Нет слова "треков" с нужным окончанием


https://github.com/user-attachments/assets/a48f0a3a-7a3d-4de0-a350-34b55de2b82b

2024-11-27 08:43 UTC, DmitrijEgorow commented
- [ ] Прогресс воспроизведения не обновляется раз в 300 миллисекунд
- [ ] Название трека и исполнитель уезжают за границы экрана


https://github.com/user-attachments/assets/c28150ee-9dfc-48d1-9799-55f1f22253e0

2024-11-27 08:50 UTC, DmitrijEgorow requested changes

2024-11-27 08:50 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/library/data/db/PlaylistsRepositoryImpl.kt
> +            )*/
Закомментированный код лучше не вливать в master

2024-11-27 08:50 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/library/data/db/entity/PlaylistEntity.kt
>      var jsonTrackIDs: String
Лучше оставить в [data class только неизменяемые свойства](https://www.reddit.com/r/Kotlin/comments/qibnqc/comment/hijhupt/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

2024-11-27 08:50 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/library/domain/api/OnLongTrackClick.kt
> +interface OnLongTrackClick {
А без него нельзя обойтись?
Не выглядит как что-то кастомное для приложения

2024-11-27 08:50 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/library/ui/fragments/PlaylistEditInfoFragment.kt
> +        createPlaylistButton.setText("Сохранить")
Лучше string-res

2024-11-27 08:50 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/library/ui/fragments/PlaylistFragment.kt
> +        binding.playlistFragmentDurationText.setText(
```suggestion
        with(binding) {
                playlistFragmentArtwork.setImageURI(playlist.artwork.toUri())
                playlistFragmentName.setText(playlist.playlistName)
                ...
        }
```

2024-11-27 08:50 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/search/ui/TrackAdapter.kt
>      fun update(tracks: ArrayList<Track>) {
```suggestion
    fun update(tracks: List<Track>) {
```

2024-11-27 08:50 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/search/ui/TrackAdapter.kt
>      private var tracks: ArrayList<Track>,
```suggestion
    private var tracks: List<Track>,
```

Нам не важна конкретная реализация списка

2024-11-27 08:50 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/sharing/domain/impl/SharingInteractorImpl.kt
>          //return getString(R.string.agreement_link)
Здесь тоже нужно использовать ресурсы

2024-11-27 08:50 UTC, DmitrijEgorow commented on app/src/main/res/values/styles.xml
>      <dimen name="text_size12">12dp</dimen>
А почему здесь text size не в sp?

2024-11-28 18:48 UTC, DmitrijEgorow commented
> * [x]  При удалении треков в одном плейлисте они удаляются во всех, приходим к неконсистентному состоянию
> 
>     * [x]  Нет слова "треков" с нужным окончанием
> 
>     * [x]  Нет вертикального отступа между названием плейлиста и его обложкой, название приклеивается к обложке
> 
> 
> Screen_recording_20241127_110448.mp4

[]  Нет вертикального отступа между названием плейлиста и его обложкой, название приклеивается к обложке
Актуально

2024-11-28 18:48 UTC, DmitrijEgorow commented
> * [x]  Кнопка сердечка не соответствует дизайну
>       ![Screenshot_20241127_110235](https://private-user-images.githubusercontent.com/36837067/390330090-1d9e1dbd-7cc4-4de7-b48f-29cceb7a1170.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MTYwMzMsIm5iZiI6MTczMjgxNTczMywicGF0aCI6Ii8zNjgzNzA2Ny8zOTAzMzAwOTAtMWQ5ZTFkYmQtN2NjNC00ZGU3LWI0OGYtMjljY2ViN2ExMTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDE3NDIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNTA4MmIwMmU1MzQ5OTFjNjRlNWZjNWIzNGQ0NWQzYTU5NzRkNmI2YjdiNjBhY2JkNmY5NmFiZmY0MTFkMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iL37XFIcks0qhQ6Mg6Gx8gnXZjs23nc0dKimv5D_pZA)

Актуально

2024-11-28 19:47 UTC, DmitrijEgorow commented
- [ ] Исчез плейсхолдер слева от названия
![Screenshot_20241128_220603](https://github.com/user-attachments/assets/9d55d329-7e9d-4274-b197-4212d857bac5)

2024-11-28 19:47 UTC, DmitrijEgorow commented
- [ ] На экране медиатеки показывает "0 треков", хотя плейлист не пуст

https://github.com/user-attachments/assets/97486a06-d4fe-4b08-8ac0-4a8b234e15bd

2024-11-28 19:48 UTC, DmitrijEgorow commented
- [ ] Приложение аварийно завершается

https://github.com/user-attachments/assets/147550fe-bf28-4db3-97f1-927a5873f2cd

```
FATAL EXCEPTION: main  
Process: com.practicum.playlistmaker, PID: 3913  
java.lang.IllegalStateException: View android.widget.LinearLayout{a5cb7d6 V.E...... ........ 0,0-1080,2014} does not have a NavController set  
at androidx.navigation.Navigation.findNavController(Navigation.kt:71)  
at androidx.navigation.fragment.NavHostFragment$Companion.findNavController(NavHostFragment.kt:386)  
at androidx.navigation.fragment.FragmentKt.findNavController(Fragment.kt:29)  
at com.practicum.playlistmaker.library.ui.fragments.PlaylistsFragment.onClick(PlaylistsFragment.kt:112)  
at com.practicum.playlistmaker.library.ui.LibraryPlaylistAdapter.openPlayerDebounce(LibraryPlaylistAdapter.kt:62)  
at com.practicum.playlistmaker.library.ui.LibraryPlaylistAdapter.onBindViewHolder$lambda$0(LibraryPlaylistAdapter.kt:53)  
at com.practicum.playlistmaker.library.ui.LibraryPlaylistAdapter.r8lambda$XpqQ_5-UlpIUN8g_PgaoWxQjCH4(Unknown Source:0)  
at com.practicum.playlistmaker.library.ui.LibraryPlaylistAdapterExternalSyntheticLambda0.onClick(D8SyntheticClass:0)  
at android.view.View.performClick(View.java:7892)  
at android.view.View.performClickInternal(View.java:7869)  
at android.view.View.-$NestmperformClickInternal(Unknown Source:0)
```

2024-11-28 19:49 UTC, DmitrijEgorow commented
- [ ] Плейсхолдер об отсутствии избранных треков накладывается на список таких треков
- [ ] Кнопка сердечка не соответствует дизайну

https://github.com/user-attachments/assets/51c5c3b6-1c81-4a42-ac3a-72aafbb8b9eb

2024-11-28 19:49 UTC, DmitrijEgorow commented
- [ ] Нет нижнего меню
![Screenshot_20241128_215127](https://github.com/user-attachments/assets/67b1c9aa-7cb7-49d1-9bbf-3f034250bf83)

2024-11-28 19:50 UTC, DmitrijEgorow commented
- [ ] Нет слова "треков"
![Screenshot_20241128_215036](https://github.com/user-attachments/assets/bd7fea6f-7842-4eb1-ac9d-df41aefcabb6)

2024-11-28 20:22 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/library/domain/api/OnLongTrackClick.kt
> +interface OnLongTrackClick {
Для такого случая, наверное, можно просто в лямбду упростить

2024-11-30 16:24 UTC, mdorogov commented
@DmitrijEgorow Привет. Перенёс обработку слушателя истории в репозиторий, установил цвета, иконки и отступы по заданному макету в фигме. Добавил логику по показу добавленных треков в плейлист. Исправил ошибки из предыдущих спринтов

2024-12-01 16:26 UTC, DmitrijEgorow commented
- [ ] Если текущий трек добавлен в выбранный плейлист, то окно добавления трека в плейлист не исчезает


https://github.com/user-attachments/assets/a26ea742-eec4-453b-86a5-db8d1bbed40d

2024-12-01 16:27 UTC, DmitrijEgorow commented
- [ ] На экране поиска нижнее меню навигации должно быть всегда

https://github.com/user-attachments/assets/09d7af50-be77-4180-851d-d8922cd3ff51

2024-12-01 16:28 UTC, DmitrijEgorow commented
- [ ] Когда на экране видна клавиатура, меню навигации должно быть скрыто за ней

https://github.com/user-attachments/assets/3959bf8b-dd7a-4790-8795-b279facf5cfc

2024-12-01 16:29 UTC, DmitrijEgorow commented
> * [x]  Плейсхолдер об отсутствии избранных треков накладывается на список таких треков
> * [x]  Кнопка сердечка не соответствует дизайну
> 
>  Screen_recording_20241128_215210.mp4

Про кнопку актуально

2024-12-01 16:31 UTC, mdorogov commented
@DmitrijEgorow Дмитрий, привет. Уточни, пожалуйста, с какими файлами и где у меня работа не соответствует архитектуре. Есть чёткий чек лист по работе интерфейса? На прошлых спринтах замечания не делались, что странно.

2024-12-01 16:33 UTC, DmitrijEgorow commented on app/src/main/java/com/practicum/playlistmaker/library/ui/fragments/PlaylistCreatingFragment.kt
Фрагмент не должен создавать директории, работать с файлами – это data слой

2024-12-01 16:34 UTC, DmitrijEgorow commented
>  Есть чёткий чек лист по работе интерфейса? 

Что значит "работа интерфейса"?

2024-12-01 16:35 UTC, DmitrijEgorow commented
> На прошлых спринтах

На то он и финальный спринт для этого приложения

2024-12-01 16:45 UTC, mdorogov commented on app/src/main/java/com/practicum/playlistmaker/library/ui/fragments/PlaylistCreatingFragment.kt
@DmitrijEgorow Спасибо, что указал на эту ошибку

2024-12-01 16:55 UTC, DmitrijEgorow commented
> > > Есть чёткий чек лист по работе интерфейса?
> > 
> > 
> > Что значит "работа интерфейса"?
> 
> @DmitrijEgorow что открывается, что не закрывается при различных действиях пользователя. С каждой проверкой что-то новое.

Если есть сомнения, всегда можно консультироваться с наставниками

2024-12-04 06:40 UTC, mdorogov commented
@DmitrijEgorow Дмитрий, привет. Посмотри, пожалуйста, правки!

2024-12-04 08:25 UTC, DmitrijEgorow approved these changes

2025-02-13 21:02 UTC, merged